// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © theEccentricTrader
//@version=5

/// Triple Top Patterns /// 

indicator('Triple Top Patterns [theEccentricTrader]', overlay = true, max_lines_count = 500, max_labels_count = 50)


//////////// shsl //////////// 


shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

addUnbrokenTrough = input(defval = false, title = 'Unbroken Troughs', group = 'Logic')
unbrokenTrough = addUnbrokenTrough ? low > trough : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

thirdPeakRatio = (peak - slPriceOne) / (shPriceTwo - slPriceOne) * 100

lowerTolerance = input(defval = 10, title = 'Lower Tolerance (%)', group = 'Tolerances')
upperTolerance = input(defval = 10, title = 'Upper Tolerance (%)', group = 'Tolerances')

tripleTop = shPrice and unbrokenTrough
 and shRangeRatio >= 100 - lowerTolerance 
 and shRangeRatio <= 100 + upperTolerance
 and thirdPeakRatio >= 100 - lowerTolerance 
 and thirdPeakRatio <= 100 + upperTolerance


//////////// lines //////////// 


patternColor = input(defval = color.blue, title = 'Pattern Color', group = 'Pattern Lines')
necklineColor = input(defval = color.yellow, title = 'Neckline Color', group = 'Pattern Lines')

selectNecklineExtend = input.string(title = 'Extend Current Neckline Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Pattern Lines")
extendNeckLine = selectNecklineExtend == 'None' ? extend.none : selectNecklineExtend == 'Right' ? extend.right : 
 selectNecklineExtend == 'Left' ? extend.left : selectNecklineExtend == 'Both' ? extend.both : na

showLabels = input(defval = true, title = 'Show Labels', group = 'Labels')
labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentNeckLine = line.new(na, na, na, na, extend = extendNeckLine, color = necklineColor, width = 2)

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if tripleTop 
    lineOne = line.new(shPriceBarIndexTwo, shPriceTwo, slPriceBarIndexOne, slPriceOne, color = patternColor, width = 2)
    lineTwo = line.new(slPriceBarIndexOne, slPriceOne, shPriceBarIndexOne, shPriceOne, color = patternColor, width = 2)
    lineThree = line.new(shPriceBarIndexOne, shPriceOne, troughBarIndex, trough, color = patternColor, width = 2)
    lineFour = line.new(troughBarIndex, trough, peakBarIndex, peak, color = patternColor, width = 2)
    lineFive = line.new(shPriceBarIndexTwo, shPriceTwo, bar_index, shPriceTwo, color = patternColor, width = 2)
    lineSix = line.new(troughBarIndex, trough, bar_index, trough, color = necklineColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? trough : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceTwo - slPriceOne) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? peak + (shPriceTwo - slPriceOne) : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceTwo - slPriceOne) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough - (shPriceTwo - slPriceOne) : na, color = color.red, style = line.style_dashed)
    line.set_xy1(currentNeckLine, troughBarIndex, trough)
    line.set_xy2(currentNeckLine, bar_index, trough)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceTwo - slPriceOne) : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? peak + (shPriceTwo - slPriceOne) : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceTwo - slPriceOne) : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? trough - (shPriceTwo - slPriceOne) : na)
    labelOne = label.new(showLabels ? peakBarIndex : na, showLabels ? peak : na, 'TRIPLE TOP', color = color.rgb(54, 58, 69, 100), style = label.style_label_down, textcolor = labelColor)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, lineFour)
    array.push(myLineArray, lineFive) 
    array.push(myLineArray, lineSix)
    array.push(myLineArray, patternPeak) 
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection) 
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    if array.size(myLabelArray) >= 50
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Triple Top')






/// Triple Bottom Patterns /// 



shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

addUnbrokenPeak = input(defval = false, title = 'Unbroken Peaks', group = 'Logic')
unbrokenPeak = addUnbrokenPeak ? high < peak : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

thirdTroughRatio = (shPriceOne - trough) / (shPriceOne - slPriceTwo) * 100

lowerTolerance = input(defval = 10, title = 'Lower Tolerance (%)', group = 'Tolerances')
upperTolerance = input(defval = 10, title = 'Upper Tolerance (%)', group = 'Tolerances')

tripleBottom = slPrice and unbrokenPeak
 and slRangeRatio >= 100 - lowerTolerance 
 and slRangeRatio <= 100 + upperTolerance
 and thirdTroughRatio >= 100 - lowerTolerance 
 and thirdTroughRatio <= 100 + upperTolerance


//////////// lines //////////// 


patternColor = input(defval = color.blue, title = 'Pattern Color', group = 'Pattern Lines')
necklineColor = input(defval = color.yellow, title = 'Neckline Color', group = 'Pattern Lines')

selectNecklineExtend = input.string(title = 'Extend Current Neckline Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Pattern Lines")
extendNeckLine = selectNecklineExtend == 'None' ? extend.none : selectNecklineExtend == 'Right' ? extend.right : 
 selectNecklineExtend == 'Left' ? extend.left : selectNecklineExtend == 'Both' ? extend.both : na

showLabels = input(defval = true, title = 'Show Labels', group = 'Labels')
labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentNeckLine = line.new(na, na, na, na, extend = extendNeckLine, color = necklineColor, width = 2)

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if tripleBottom 
    lineOne = line.new(slPriceBarIndexTwo, slPriceTwo, shPriceBarIndexOne, shPriceOne, color = patternColor, width = 2)
    lineTwo = line.new(shPriceBarIndexOne, shPriceOne, slPriceBarIndexOne, slPriceOne, color = patternColor, width = 2)
    lineThree = line.new(slPriceBarIndexOne, slPriceOne, peakBarIndex, peak, color = patternColor, width = 2)
    lineFour = line.new(peakBarIndex, peak, troughBarIndex, trough, color = patternColor, width = 2)
    lineFive = line.new(slPriceBarIndexTwo, slPriceTwo, bar_index, slPriceTwo, color = patternColor, width = 2)
    lineSix = line.new(peakBarIndex, peak, bar_index, peak, color = necklineColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? trough : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceOne - slPriceTwo) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? peak + (shPriceOne - slPriceTwo) : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - slPriceTwo) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough - (shPriceOne - slPriceTwo) : na, color = color.red, style = line.style_dashed)
    line.set_xy1(currentNeckLine, peakBarIndex, peak)
    line.set_xy2(currentNeckLine, bar_index, peak)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceOne - slPriceTwo) : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? peak + (shPriceOne - slPriceTwo) : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - slPriceTwo) : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? trough - (shPriceOne - slPriceTwo) : na)
    labelOne = label.new(showLabels ? troughBarIndex : na, showLabels ? trough : na, 'TRIPLE BOTTOM', color = color.rgb(54, 58, 69, 100), style = label.style_label_up, textcolor = labelColor)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, lineFour)
    array.push(myLineArray, lineFive) 
    array.push(myLineArray, lineSix)
    array.push(myLineArray, patternPeak) 
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection) 
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    if array.size(myLabelArray) >= 50
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Triple Bottom')
 




/// Double Top Patterns /// 


shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

addUnbrokenTrough = input(defval = false, title = 'Unbroken Troughs', group = 'Logic')
unbrokenTrough = addUnbrokenTrough ? low > trough : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

bcLowerTolerance = input(defval = 10, title = 'BC Lower Tolerance (%)', group = 'Tolerances')
bcUpperTolerance = input(defval = 10, title = 'BC Upper Tolerance (%)', group = 'Tolerances')

doubleTop = shPrice and unbrokenTrough
 and shRangeRatio >= 100 - bcLowerTolerance 
 and shRangeRatio <= 100 + bcUpperTolerance


//////////// lines //////////// 


patternColor = input(defval = color.blue, title = 'Pattern Color', group = 'Pattern Lines')
necklineColor = input(defval = color.yellow, title = 'Neckline Color', group = 'Pattern Lines')

selectNecklineExtend = input.string(title = 'Extend Current Neckline Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Pattern Lines")
extendNeckLine = selectNecklineExtend == 'None' ? extend.none : selectNecklineExtend == 'Right' ? extend.right : 
 selectNecklineExtend == 'Left' ? extend.left : selectNecklineExtend == 'Both' ? extend.both : na

showLabels = input(defval = true, title = 'Show Labels', group = 'Labels')
labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentNeckLine = line.new(na, na, na, na, extend = extendNeckLine, color = necklineColor, width = 2)

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if doubleTop 
    lineOne = line.new(shPriceBarIndexOne, shPriceOne, troughBarIndex, trough, color = patternColor, width = 2)
    lineTwo = line.new(troughBarIndex, trough, peakBarIndex, peak, color = patternColor, width = 2)
    lineThree = line.new(shPriceBarIndexOne, shPriceOne, bar_index, shPriceOne, color = patternColor, width = 2)
    lineFour = line.new(troughBarIndex, trough, bar_index, trough, color = necklineColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? trough : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceOne - trough) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? peak + (shPriceOne - trough) : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - trough) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough - (shPriceOne - trough) : na, color = color.red, style = line.style_dashed)
    labelOne = label.new(showLabels ? peakBarIndex : na, showLabels ? peak : na, 'DOUBLE TOP', color = color.rgb(54, 58, 69, 100), style = label.style_label_down, textcolor = labelColor)
    line.set_xy1(currentNeckLine, troughBarIndex, trough)
    line.set_xy2(currentNeckLine, bar_index, trough)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? peakBarIndex : na, showProjections ? peak + (shPriceOne - trough) : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? peak + (shPriceOne - trough) : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - trough) : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? trough - (shPriceOne - trough) : na)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, lineFour)
    array.push(myLineArray, patternPeak) 
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection) 
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    if array.size(myLabelArray) >= 63
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Double Top')




/// Double Bottom Patterns /// 



shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

addUnbrokenPeak = input(defval = false, title = 'Unbroken Peaks', group = 'Logic')
unbrokenPeak = addUnbrokenPeak ? high < peak : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

lowerTolerance = input(defval = 10, title = 'Lower Tolerance (%)', group = 'Tolerances')
upperTolerance = input(defval = 10, title = 'Upper Tolerance (%)', group = 'Tolerances')

doubleBottom = slPrice and unbrokenPeak
 and slRangeRatio >= 100 - lowerTolerance 
 and slRangeRatio <= 100 + upperTolerance


//////////// lines //////////// 


patternColor = input(defval = color.blue, title = 'Pattern Color', group = 'Pattern Lines')
necklineColor = input(defval = color.yellow, title = 'Neckline Color', group = 'Pattern Lines')

selectNecklineExtend = input.string(title = 'Extend Current Neckline Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Pattern Lines")
extendNeckLine = selectNecklineExtend == 'None' ? extend.none : selectNecklineExtend == 'Right' ? extend.right : 
 selectNecklineExtend == 'Left' ? extend.left : selectNecklineExtend == 'Both' ? extend.both : na

showLabels = input(defval = true, title = 'Show Labels', group = 'Labels')
labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentNeckLine = line.new(na, na, na, na, extend = extendNeckLine, color = necklineColor, width = 2)

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if doubleBottom 
    lineOne = line.new(slPriceBarIndexOne, slPriceOne, peakBarIndex, peak, color = patternColor, width = 2)
    lineTwo = line.new(peakBarIndex, peak, troughBarIndex, trough, color = patternColor, width = 2)
    lineThree = line.new(slPriceBarIndexOne, slPriceOne, bar_index, slPriceOne, color = patternColor, width = 2)
    lineFour = line.new(peakBarIndex, peak, bar_index, peak, color = necklineColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? trough : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? peakBarIndex : na, showProjections ? peak + (peak - slPriceOne) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? peak + (peak - slPriceOne) : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? troughBarIndex : na, showProjections ? trough - (peak - slPriceOne) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough - (peak - slPriceOne) : na, color = color.red, style = line.style_dashed)
    labelOne = label.new(showLabels ? troughBarIndex : na, showLabels ? trough : na, 'DOUBLE BOTTOM', color = color.rgb(54, 58, 69, 100), style = label.style_label_up, textcolor = labelColor)
    line.set_xy1(currentNeckLine, peakBarIndex, peak)
    line.set_xy2(currentNeckLine, bar_index, peak)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? peakBarIndex : na, showProjections ? peak + (peak - slPriceOne) : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? peak + (peak - slPriceOne) : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? troughBarIndex : na, showProjections ? trough - (peak - slPriceOne) : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? trough - (peak - slPriceOne) : na)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, lineFour)
    array.push(myLineArray, patternPeak) 
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection) 
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    if array.size(myLabelArray) >= 63
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Double Bottom')
 



/// Bearish Alternate Flag Patterns /// 


shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

returnLineUptrend = ta.valuewhen(shPrice, shPrice, 0) > ta.valuewhen(shPrice, shPrice, 1)
uptrend = ta.valuewhen(slPrice, slPrice, 0) > ta.valuewhen(slPrice, slPrice, 1)
downtrend = ta.valuewhen(shPrice, shPrice, 0) < ta.valuewhen(shPrice, shPrice, 1)
returnLineDowntrend = ta.valuewhen(slPrice, slPrice, 0) < ta.valuewhen(slPrice, slPrice, 1)

addUnbrokenTrough = input(defval = false, title = 'Unbroken Troughs', group = 'Logic')
unbrokenTrough = addUnbrokenTrough ? low > trough : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

slRangeRatioZero = ta.valuewhen(slPrice, slRangeRatio, 0)
slRangeRatioOne = ta.valuewhen(slPrice, slRangeRatio, 1)

shRangeRatioZero = ta.valuewhen(shPrice, shRangeRatio, 0)
shRangeRatioOne = ta.valuewhen(shPrice, shRangeRatio, 1)

abRatio = input(defval = 100, title = 'AB Maximum Ratio', group = 'Range Ratios')
bcRatio = input(defval = 30, title = 'BC Maximum Ratio', group = 'Range Ratios')

bearishAlternateFlag = shPrice and downtrend and unbrokenTrough
 and slRangeRatioZero >= abRatio 
 and shRangeRatio <= bcRatio 


//////////// lines //////////// 


poleColor = input(defval = color.blue, title = 'Pole Color', group = 'Pattern Lines')
flagColor = input(defval = color.red, title = 'Flag Color', group = 'Pattern Lines')

labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if bearishAlternateFlag 
    lineOne = line.new(shPriceBarIndexOne, shPriceOne, troughBarIndex, trough, color = poleColor, width = 2)
    lineTwo = line.new(troughBarIndex, trough, shPriceBarIndex, shPrice, color = flagColor, width = 2)
    lineThree = line.new(shPriceBarIndex - 1, shPrice, shPriceBarIndex, shPrice, color = flagColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? trough : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? shPriceBarIndexOne : na, showProjections ? shPriceOne : na, showProjections ? bar_index + 1 : na, 
     showProjections ? shPriceOne : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - trough) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? trough - (shPriceOne - trough) : na, color = color.red, style = line.style_dashed)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? shPriceBarIndexOne : na, showProjections ? shPriceOne : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? shPriceOne : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? troughBarIndex : na, showProjections ? trough - (shPriceOne - trough) : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? trough - (shPriceOne - trough) : na)
    labelOne = label.new(shPriceBarIndexOne, shPriceOne, color = color.rgb(54, 58, 69, 100), style = label.style_label_down,
     text = 'A', textcolor = labelColor)
    labelTwo = label.new(troughBarIndex, trough, color = color.rgb(54, 58, 69, 100), style = label.style_label_up,
     text = 'B (' + str.tostring(math.round(slRangeRatioZero, 2)) + ')', textcolor = labelColor)
    labelThree = label.new(shPriceBarIndex, shPrice, color = color.rgb(54, 58, 69, 100), style = label.style_label_down,
     text = 'C (' + str.tostring(math.round(shRangeRatio, 2)) + ')', textcolor = labelColor)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, patternPeak)
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection)
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    array.push(myLabelArray, labelTwo)
    array.push(myLabelArray, labelThree)
    if array.size(myLabelArray) >= 250
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Bearish Alt. Flag')

    
 

/// Bullish Alternate Flag Patterns /// 


shPrice = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? high : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? high[1] : na
shPriceBarIndex = close[1] >= open[1] and close < open and high >= high[1] and barstate.isconfirmed ? bar_index : 
 close[1] >= open[1] and close < open and high <= high[1] and barstate.isconfirmed ? bar_index - 1 : na
peak = ta.valuewhen(shPrice, shPrice, 0)
peakBarIndex = ta.valuewhen(shPrice, shPriceBarIndex, 0)
shPriceOne = ta.valuewhen(shPrice, shPrice, 1)
shPriceBarIndexOne = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 1)
shPriceTwo = ta.valuewhen(shPrice, shPrice, 2)
shPriceBarIndexTwo = ta.valuewhen(shPriceBarIndex, shPriceBarIndex, 2)

slPrice = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? low : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? low[1] : na
slPriceBarIndex = close[1] < open[1] and close >= open and low <= low[1] and barstate.isconfirmed ? bar_index : 
 close[1] < open[1] and close >= open and low >= low[1] and barstate.isconfirmed ? bar_index - 1 : na
trough = ta.valuewhen(slPrice, slPrice, 0)
troughBarIndex = ta.valuewhen(slPrice, slPriceBarIndex, 0)
slPriceOne = ta.valuewhen(slPrice, slPrice, 1)
slPriceBarIndexOne = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 1)
slPriceTwo = ta.valuewhen(slPrice, slPrice, 2)
slPriceBarIndexTwo = ta.valuewhen(slPriceBarIndex, slPriceBarIndex, 2)

returnLineUptrend = ta.valuewhen(shPrice, shPrice, 0) > ta.valuewhen(shPrice, shPrice, 1)
uptrend = ta.valuewhen(slPrice, slPrice, 0) > ta.valuewhen(slPrice, slPrice, 1)
downtrend = ta.valuewhen(shPrice, shPrice, 0) < ta.valuewhen(shPrice, shPrice, 1)
returnLineDowntrend = ta.valuewhen(slPrice, slPrice, 0) < ta.valuewhen(slPrice, slPrice, 1)

addUnbrokenPeak = input(defval = false, title = 'Unbroken Peaks', group = 'Logic')
unbrokenPeak = addUnbrokenPeak ? high < peak : true

slRangeRatio = (peak - trough) / (peak - trough[1]) * 100
shRangeRatio = (peak - trough) / (peak[1] - trough) * 100

slRangeRatioZero = ta.valuewhen(slPrice, slRangeRatio, 0)
slRangeRatioOne = ta.valuewhen(slPrice, slRangeRatio, 1)

shRangeRatioZero = ta.valuewhen(shPrice, shRangeRatio, 0)
shRangeRatioOne = ta.valuewhen(shPrice, shRangeRatio, 1)

abRatio = input(defval = 100, title = 'AB Minimum Ratio', group = 'Range Ratios')
bcRatio = input(defval = 30, title = 'BC Maximum Ratio', group = 'Range Ratios')

bullishAlternateFlag = slPrice and uptrend and unbrokenPeak
 and shRangeRatioZero >= abRatio 
 and slRangeRatio <= bcRatio 


//////////// lines //////////// 


poleColor = input(defval = color.blue, title = 'Pole Color', group = 'Pattern Lines')
flagColor = input(defval = color.green, title = 'Flag Color', group = 'Pattern Lines')

labelColor = input(defval = color.blue, title = 'Label Color', group = 'Labels')

showProjections = input(defval = true, title = 'Show Projections', group = 'Projection Lines')

selectProjectionExtend = input.string(title = 'Extend Current Projection Lines', defval = 'None', options = ['None', 'Right', 'Left', 'Both'], group = "Projection Lines")
extendProjectionLines = selectProjectionExtend == 'None' ? extend.none : selectProjectionExtend == 'Right' ? extend.right : 
 selectProjectionExtend == 'Left' ? extend.left : selectProjectionExtend == 'Both' ? extend.both : na

var currentPatternPeak = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternTrough = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)
var currentPatternUpperProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.green, style = line.style_dashed)
var currentPatternLowerProjection = line.new(na, na, na, na, extend = extendProjectionLines, color = color.red, style = line.style_dashed)

if bullishAlternateFlag 
    lineOne = line.new(slPriceBarIndexOne, slPriceOne, peakBarIndex, peak, color = poleColor, width = 2)
    lineTwo = line.new(peakBarIndex, peak, slPriceBarIndex, slPrice, color = flagColor, width = 2)
    lineThree = line.new(slPriceBarIndex - 1, slPrice, slPriceBarIndex, slPrice, color = flagColor, width = 2)
    patternPeak = line.new(showProjections ? peakBarIndex : na, showProjections ? peak : na, showProjections ? bar_index + 1  : na, 
     showProjections ? peak : na, color = color.green, style = line.style_dashed)
    patternTrough = line.new(showProjections ? troughBarIndex : na, showProjections ? slPrice : na, showProjections ? bar_index + 1 : na, 
     showProjections ? slPrice : na, color = color.red, style = line.style_dashed)
    patternUpperProjection = line.new(showProjections ? peakBarIndex : na, showProjections ? peak + (peak - slPriceOne) : na, showProjections ? bar_index + 1 : na, 
     showProjections ? peak + (peak - slPriceOne) : na, color = color.green, style = line.style_dashed)
    patternLowerProjection = line.new(showProjections ? slPriceBarIndexOne : na, showProjections ? slPriceOne : na, showProjections ? bar_index + 1 : na, 
     showProjections ? slPriceOne : na, color = color.red, style = line.style_dashed)
    line.set_xy1(currentPatternPeak, showProjections ? peakBarIndex : na, showProjections ? peak : na)
    line.set_xy2(currentPatternPeak, showProjections ? bar_index + 1 : na, showProjections ? peak : na)
    line.set_xy1(currentPatternTrough, showProjections ? troughBarIndex : na, showProjections ? trough : na)
    line.set_xy2(currentPatternTrough, showProjections ? bar_index + 1 : na, showProjections ? trough : na)
    line.set_xy1(currentPatternUpperProjection, showProjections ? peakBarIndex : na, showProjections ? peak + (peak - slPriceOne) : na)
    line.set_xy2(currentPatternUpperProjection, showProjections ? bar_index + 1 : na, showProjections ? peak + (peak - slPriceOne) : na)
    line.set_xy1(currentPatternLowerProjection, showProjections ? slPriceBarIndexOne : na, showProjections ? slPriceOne : na)
    line.set_xy2(currentPatternLowerProjection, showProjections ? bar_index + 1 : na, showProjections ? slPriceOne : na)
    labelOne = label.new(slPriceBarIndexOne, slPriceOne, color = color.rgb(54, 58, 69, 100), style = label.style_label_up,
     text = 'A', textcolor = labelColor)
    labelTwo = label.new(peakBarIndex, peak, color = color.rgb(54, 58, 69, 100), style = label.style_label_down,
     text = 'B (' + str.tostring(math.round(shRangeRatioZero, 2)) + ')', textcolor = labelColor)
    labelThree = label.new(slPriceBarIndex, slPrice, color = color.rgb(54, 58, 69, 100), style = label.style_label_up,
     text = 'C (' + str.tostring(math.round(slRangeRatio, 2)) + ')', textcolor = labelColor)
    var myLineArray = array.new_line()
    array.push(myLineArray, lineOne) 
    array.push(myLineArray, lineTwo) 
    array.push(myLineArray, lineThree) 
    array.push(myLineArray, patternPeak)
    array.push(myLineArray, patternTrough) 
    array.push(myLineArray, patternUpperProjection)
    array.push(myLineArray, patternLowerProjection)
    if array.size(myLineArray) >= 500
        firstLine = array.remove(myLineArray, 0) 
        line.delete(firstLine)
    var myLabelArray = array.new_label()
    array.push(myLabelArray, labelOne)
    array.push(myLabelArray, labelTwo)
    array.push(myLabelArray, labelThree)
    if array.size(myLabelArray) >= 250
        firstLabel = array.remove(myLabelArray, 0) 
        label.delete(firstLabel)
    alert('Bullish Alt. Flag')

    
 


/// Bullish Alternate Flag Patterns /// 


