// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © mikeright25

//@version=5


////Source: Built in "All Candlestick Patterns"
////Bulkowski Candlestick Percentages from his site and book.
////Built in Variables and Candles adjusted slightly to conform to Bulkowski principles.
////In this current version, I've added about 8 candles and removed some that are statistically insignificant and others that Bulkowski doesn't use. Will add back if requested. Moved inputs back to ABC order.
////I decided to leave the theoretical performance as the signal being still on Top for theoretically bearish, and the opposite for theoretically bullish; but I did adjust the signal color to match Bulkowski's tested performance.
////Removed Plot Close


indicator('complete release All Candlestick Patterns & Bulkowski Percentages 1.0', shorttitle='complete release All Candle_Ptrns_Bulkowski_Perc', overlay=true)


ttnote_perc = 'Please note: the percentages listed are based on Bulkowski\'s tested performance of the candles during a Bull Market (which we are currently in), this doesn\'t guarantee future success.'

C_DownTrend = true
C_UpTrend = true
var trendRule1 = 'SMA50'
var trendRule2 = 'SMA50, SMA200'
var trendRule = input.string(trendRule1, 'Detect Trend Based On', options=[trendRule1, trendRule2, 'No detection'])

if trendRule == trendRule1
    priceAvg = ta.sma(close, 50)
    C_DownTrend := close < priceAvg
    C_UpTrend := close > priceAvg
    C_UpTrend

if trendRule == trendRule2
    sma200 = ta.sma(close, 200)
    sma50 = ta.sma(close, 50)
    C_DownTrend := close < sma50 and sma50 < sma200
    C_UpTrend := close > sma50 and sma50 > sma200
    C_UpTrend
C_Len = 14  // ema depth for bodyAvg
C_ShadowPercent = 5.0  // size of shadows
C_ShadowEqualsPercent = 100.0
C_DojiBodyPercent = 5.0
C_Factor = 2.0  // shows the number of times the shadow dominates the candlestick body

//VARIABLES

C_BodyHi = math.max(close, open)
C_BodyLo = math.min(close, open)
C_Body = C_BodyHi - C_BodyLo
C_BodyAvg = ta.ema(C_Body, C_Len)
C_SmallBody = C_Body < C_BodyAvg
C_LongBody = C_Body > C_BodyAvg
C_UpShadow = high - C_BodyHi
C_DnShadow = C_BodyLo - low
C_HasUpShadow = C_UpShadow > C_ShadowPercent / 100 * C_Body
C_HasDnShadow = C_DnShadow > C_ShadowPercent / 100 * C_Body
C_WhiteBody = open < close
C_BlackBody = open > close
C_Range = high - low
C_IsInsideBar = C_BodyHi[1] > C_BodyHi and C_BodyLo[1] < C_BodyLo
C_BodyMiddle = C_Body / 2 + C_BodyLo
C_ShadowEquals = C_UpShadow == C_DnShadow or math.abs(C_UpShadow - C_DnShadow) / C_DnShadow * 100 < C_ShadowEqualsPercent and math.abs(C_DnShadow - C_UpShadow) / C_UpShadow * 100 < C_ShadowEqualsPercent
C_IsDojiBody = C_Range > 0 and C_Body <= C_Range * C_DojiBodyPercent / 100
C_Doji = C_IsDojiBody and C_ShadowEquals

patternLabelPosLow = low - ta.atr(30) * 0.6
patternLabelPosHigh = high + ta.atr(30) * 0.6

label_color_bullish = input(color.blue, 'Label Color Bullish')
label_color_bearish = input(color.red, 'Label Color Bearish')
label_color_neutral = input(color.gray, 'Label Color Neutral')
label_color_bullcont = input(color.new(color.aqua, 60), 'Label Color Bullish Continuation')
label_color_bearcont = input(color.new(color.orange, 60), 'Label Color Bearish Continuation')

CandleType = input.string(title='Pattern Type', defval='Both', options=['Bullish', 'Bearish', 'Both'], tooltip=ttnote_perc)

AbandonedBabyInput = input(title='Abandoned Baby (Bullish=70% rev./ Bearish=69% rev.)', defval=true)
AboveTheStomachInput = input(title='Above The Stomach (Bullish reversal 66%)', defval=true)
Bullish_BeltHoldInput = input(title='Bullish Bult Hold (Bullish reversal 71%)', defval=true)
DarkCloudCoverInput = input(title='Dark Cloud Cover (Bearish reversal 60%)', defval=true)
DeliberationInput = input(title='Deliberation (Bullish contin. 77%)', defval=true)
DojiInput = input(title='Doji (Bullish contin. 51%)', defval=true)
DojiStarInput = input(title='Doji Star', defval=true)
DownsideTasukiGapInput = input(title='Downside Tasuki Gap (Bullish reversal 54%) ', defval=true)
DragonflyDojiInput = input(title='Dragonfly Doji (Bullish contin. 51%)', defval=true)
EngulfingInput = input(title='Engulfing (Bullish=rev. 63%/ Bearish=rev. 79%)', defval=true)
EveningDojiStarInput = input(title='Evening Doji Star (Bearish reversal 71%)', defval=true)
EveningStarInput = input(title='Evening Star (Bearish reversal 72%)', defval=true)
FallingThreeMethodsInput = input(title='Falling Three Methods (Bearish contin. 71%)', defval=true)
FallingWindowInput = input(title='Falling Window', defval=true)
GravestoneDojiInput = input(title='Gravestone Doji', defval=true)
HammerInput = input(title='Hammer', defval=true)
Inverted_HammerInput = input(title='Inverted Hammer (Bearish contin. 65%)', defval=true)
HangingManInput = input(title='Hanging Man', defval=true)
HaramiCrossInput = input(title='Harami Cross (Bullish contin. 57%)', defval=true)
HaramiInput = input(title='Harami', defval=true)
IdenticalThreeCrowsInput = input(title='Identical Three Crows (Bearish reversal 79%)', defval=true)
KickingInput = input(title='Kicking (Bullish reversal 53%)', defval=true)
// LongLowerShadowInput = input(title = "Long Lower Shadow" ,defval=false)
// LongUpperShadowInput = input(title = "Long Upper Shadow" ,defval=false)
MarubozuBlackInput = input(title = "Marubozu Black" ,defval=false)
MarubozuWhiteInput = input(title = "Marubozu White" ,defval=false)
MorningDojiStarInput = input(title='Morning Doji Star (Bullish reversal 76%)', defval=true)
MorningStarInput = input(title='Morning Star (Bullish reversal 78%)', defval=true)
OnNeckInput = input(title='On Neck (Bearish contin. 56%)', defval=true)
PiercingInput = input(title='Piercing (Bullish reversal 64%)', defval=true)
RisingThreeMethodsInput = input(title='Rising Three Methods (Bullish contin. 74%)', defval=true)
RisingWindowInput = input(title='Rising Window (Bullish contin. 75%)', defval=true)
ShootingStarInput = input(title='Shooting Star (Bearish reversal 59%)', defval=true)
SpinningTopBlackInput = input(title='Spinning Top Black (Reversal 51%)', defval=true)
SpinningTopWhiteInput = input(title='Spinning Top White (Reversal 50%)', defval=true)
ThreeBlackCrowsInput = input(title='Three Black Crows (Bearish reversal 78%)', defval=true)
Bearish_ThreeLineStrikeInput = input(title='Bearish Three Line Strike (Bullish reversal 84%)', defval=true)
Bullish_ThreeLineStrikeInput = input(title='Bullish Three Line Strike (Bearish reversal 83%)', defval=true)
ThreeOutsideUpInput = input(title='Three Outside Up (Bullish reversal 75%)', defval=true)
ThreeWhiteSoldiersInput = input(title='Three White Soldiers (Bullish reversal 82%)', defval=true)
TriStarInput = input(title='Tri-Star (Bullish reversal 60%)', defval=true)
TweezerBottomInput = input(title='Tweezer Bottom (Bearish contin. 52%)', defval=true)
TweezerTopInput = input(title='Tweezer Top (Bullish contin. 56%)', defval=true)
UpsideTasukiGapInput = input(title='Upside Tasuki Gap (Bullish contin. 57%)', defval=true)



C_AboveTheStomachNumberOfCandles = 2
C_AboveTheStomach = false
if C_DownTrend and C_WhiteBody and C_BlackBody[1]
    C_AboveTheStomach := open[3] > close[3] and open[2] > close[2] and open[1] > close[1] and open < close and high[1] <= close and close[1] <= open and open[1] >= open
    C_AboveTheStomach
alertcondition(C_AboveTheStomach, title='Above The Stomach', message='New Above The Stomach (Bullish reversal) pattern detected')
if C_AboveTheStomach and AboveTheStomachInput and ('Bullish' == CandleType or CandleType == 'Both')
    //var ttAboveTheStomach = 'Above The Stomach\nBullish reversal 66% of the time. Overall performance rank: 31. Look for two candles in a downward price trend. The first candle is black and the second white. The white candle should open and close at or above the mid point of the black candle\'s body.'
    var ttAboveTheStomach = 'Above The Stomach\n下降トレンドのなかで出現したら、上げへ66%の確率で反転する'
    label.new(bar_index, patternLabelPosLow, text='ATS', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttAboveTheStomach)


C_Bullish_BeltHoldNumberOfCandles = 1
C_BBHShadowPercentWhite = 5.0
C_Bullish_BeltHold = false
if C_DownTrend and C_WhiteBody
    C_Bullish_BeltHold := open[1] > close[1] and open < close and open[1] > close and low[1] > open and C_HasUpShadow and C_LongBody and C_DnShadow <= C_BBHShadowPercentWhite / 100 * C_Body and C_WhiteBody
    C_Bullish_BeltHold
alertcondition(C_Bullish_BeltHold, title='Bullish Belt Hold', message='New Bullish Belt Hold (Bullish reversal) pattern detected')
if C_Bullish_BeltHold and Bullish_BeltHoldInput and ('Bullish' == CandleType or CandleType == 'Both')
    //var ttBullish_BeltHold = 'Bullish Belt Hold\nBullish reversal 71% of the time. Overall performance rank: 62 Look for a white candle with no lower shadow, but closing near the high. Belt hold candles taller than the median have post breakout performance significantly better than those shorter than the median. Belt holds with comparatively tall upper shadows outperform.'
    var ttBullish_BeltHold = 'Bullish Belt Hold\n上げへ71%の確率で反転する'
    label.new(bar_index, patternLabelPosLow, text='BBH', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullish_BeltHold)


C_ThreeOutsideUpNumberOfCandles = 3
C_ThreeOutsideUp = false
if C_DownTrend and C_WhiteBody and C_WhiteBody[1] and C_BlackBody[2]
    C_ThreeOutsideUp := open[3] > close[3] and open[2] > close[2] and open[1] < close[1] and open < close and open[2] <= close[1] and close[2] >= open[1] and close[1] <= open
    C_ThreeOutsideUp
alertcondition(C_ThreeOutsideUp, title='Three Outside Up', message='New Three Outside Up (Bullish reversal) pattern detected')
if C_ThreeOutsideUp and ThreeOutsideUpInput and ('Bullish' == CandleType or CandleType == 'Both')
   // var ttThreeOutsideUp = 'Three Outside Up\nBullish reversal 75% of the time. Overall performance rank: 34. Look for a black candle in a downward price trend. Following that, a white candle opens below the prior body and closes above it, too. The last day is a candle in which price closes higher, according to Morris who developed the candle. For the best performance, look for the pattern in a downward retracement of the upward price trend.'
    var ttThreeOutsideUp = 'Three Outside Up\n下降トレンドのなかで出現したら、上げへ75%の確率で反転する'
    label.new(bar_index, patternLabelPosLow, text='3OU', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttThreeOutsideUp)


C_Bullish_ThreeLineStrikeNumberOfCandles = 4
C_Bullish_ThreeLineStrike = false
if C_UpTrend and C_BlackBody and C_WhiteBody[1] and C_WhiteBody[2] and C_WhiteBody[3]
    C_Bullish_ThreeLineStrike := open[3] < close[3] and open[2] < close[2] and open[1] < close[1] and open > close and close[3] <= open[2] and close[2] <= open[1] and close[1] <= open and open[3] >= close
    C_Bullish_ThreeLineStrike

alertcondition(C_Bullish_ThreeLineStrike, title='Bullish Three-Line Strike (Bearish reversal)', message='New Bullish Three-Line Strike (bearish reversal) pattern detected')
if C_Bullish_ThreeLineStrike and Bullish_ThreeLineStrikeInput and ('Bullish' == CandleType or CandleType == 'Both')
   // var ttBullish_ThreeLineStrike = 'Bullish Three-Line Strike\nBearish reversal 65% of the time. Theoretical performance: Bullish continuation. Look for three white candles each with a higher close. A tall black candle should open higher, but close below the open of the first candle. Price forms three white candles, each with a higher close, in an upward price trend. A black candle opens higher but price plummets so that it closes below the opening price of the first candle. The next day, price gaps open lower and closes lower still, staging a downward breakout. This bullish three-line strike candlestick pattern acts as a bearish reversal of the upward price trend. That disobeys candle theory which says that this candlestick pattern acts as a continuation of the prevailing price trend.'
    var ttBullish_ThreeLineStrike = 'Bullish Three-Line Strike\n65%の確率で下げに反転。上昇トレンドの中での下げへの反転として作用する。'
    label.new(bar_index, patternLabelPosHigh, text='3LS', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBullish_ThreeLineStrike)

C_DeliberationNumberOfCandles = 3
C_Deliberation = false
if C_SmallBody and C_LongBody[1] and C_LongBody[2]
    if C_WhiteBody and C_WhiteBody[1] and C_WhiteBody[2]
        C_Deliberation := open[2] < close[2] and open[1] < close[1] and open < close and close[2] < open[1] and close[1] < open and high[2] - low[2] > high[1] - low[1] and high[1] - low[1] > high - low
        C_Deliberation
//220613ここから
alertcondition(C_Deliberation, title='Deliberation – Bullish Continuation', message='New Deliberation – Bullish Continuation pattern detected')
if C_Deliberation and DeliberationInput and ('Bullish' == CandleType or CandleType == 'Both')

    //var ttDeliberation = 'Deliberation\nBullish continuation 77% of the time. Theoretical performance: Bearish reversal. Overall performance rank: 93. Look for three white candlesticks in an upward price trend. The first two are tall bodied candles but the third has a small body that opens near the second day\'s close. Each candle opens and closes higher than the previous one. The first two candles have tall bodies but the third line has a small body. Each of the candles is supposed to open and close higher, but a higher close is tough to see on the third day. The last day should also open near the prior close. This deliberation acts as a reversal of the upward price trend because price closes below the bottom of the candle pattern first, not the top, plus, it appears in an upward price trend. Notice that the trend stops when it hits overhead resistance near the top of the candle pattern.'
    var ttDeliberation = 'Deliberation\n上昇トレンドの間に発生。強気継続77％。だが３本目の陽線が「陽のコマ」になっているもので、買いの勢いが若干衰え、相場転換の可能性がある。それが弱気反転23％'
    label.new(bar_index, patternLabelPosHigh, text='Del', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttDeliberation)

C_IdenticalThreeCrowsNumberOfCandles = 3
C_IdenticalThreeCrows = false
if C_UpTrend and C_BlackBody and C_BlackBody[1] and C_BlackBody[2]
    if open[2] > close[2] and open[1] > close[1] and open > close and close[2] >= open[1] and close[2] >= open and low[2] <= open[1] and low[1] <= open and open[2] >= high[1] and open[1] >= high and low[2] >= close[1] and low[1] >= open
        C_IdenticalThreeCrows := true
        C_IdenticalThreeCrows
alertcondition(C_IdenticalThreeCrows, title='Identical 3 Crows', message='New Bearish Identical 3 Crows pattern detected')
if C_IdenticalThreeCrows and IdenticalThreeCrowsInput and ('Bearish' == CandleType or CandleType == 'Both')
   // var ttIdenticalThreeCrows = 'Identical 3 Crows\nBearish Reversal Bearish reversal 79% of the time. Overall performance rank: 24. Look for three tall black candles, the last two opening near the prior candle\'s close. Some sources require each candle to be similar in size, but this one is rare enough without that restriction. '
    var ttIdenticalThreeCrows = 'Identical 3 Crows\n 上昇トレンドにある場合、トレンドの反転を示唆するもの。79%の確率で下げに反転。'
    label.new(bar_index, patternLabelPosHigh, text='I3C', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttIdenticalThreeCrows)


C_Bearish_ThreeLineStrikeNumberOfCandles = 4
C_Bearish_ThreeLineStrike = false
if C_DownTrend and C_WhiteBody and C_BlackBody[1] and C_BlackBody[2] and C_BlackBody[3]
    if close[3] < open[3] and close[2] < open[2] and close[2] < close[3] and close[1] < open[1] and close[1] < close[2] and open <= close[1] and close >= open[3]
        C_Bearish_ThreeLineStrike := true
        C_Bearish_ThreeLineStrike
alertcondition(C_Bearish_ThreeLineStrike, title='Bearish Three-Line Strike (bullish rev)', message='New Bearish Three-Line Strike pattern detected')
if C_Bearish_ThreeLineStrike and Bearish_ThreeLineStrikeInput and ('Bearish' == CandleType or CandleType == 'Both')

   // var ttBearish_ThreeLineStrike = '3 Line Strike\nBullish reversal 84% of the time Theoretical performance: Bearish continuation. Price forms three black candles, each with lower closes, in a downward price trend. A tall white candle engulfs the price action of the prior three days. The candle acts as a bullish reversal when price breaks out upward, and closes above the top of the candle pattern. '
    var ttBearish_ThreeLineStrike = '3 Line Strike\n84%の確率で上げに反転。下降トレンドの中で、3本の陰線を形成し、4本目の陽線が3本分飲み込む形。'
    label.new(bar_index, patternLabelPosLow, text='3LS', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBearish_ThreeLineStrike)

C_OnNeckBearishNumberOfCandles = 2
C_OnNeckBearish = false
if C_DownTrend and C_BlackBody[1] and C_LongBody[1] and C_WhiteBody and open < close[1] and C_SmallBody and C_Range != 0 and math.abs(close - low[1]) <= C_BodyAvg * 0.05
    C_OnNeckBearish := true
    C_OnNeckBearish
alertcondition(C_OnNeckBearish, title='On Neck – Bearish', message='New On Neck – Bearish pattern detected')
if C_OnNeckBearish and OnNeckInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishOnNeck = 'On Neck\nBearish continuation 56%. On Neck is a two-line continuation pattern found in a downtrend. The first candle is long and red, the second candle is short and has a green body. The closing price of the second candle is close or equal to the first candle\'s low price. The pattern hints at a continuation of a downtrend, and penetrating the low of the green candlestick is sometimes considered a confirmation. '
    label.new(bar_index, patternLabelPosHigh, text='ON', style=label.style_label_down, color=label_color_bearcont, textcolor=color.white, tooltip=ttBearishOnNeck)
C_RisingWindowBullishNumberOfCandles = 2
C_RisingWindowBullish = false
if C_UpTrend[1] and C_Range != 0 and C_Range[1] != 0 and low > high[1]
    C_RisingWindowBullish := true
    C_RisingWindowBullish
alertcondition(C_RisingWindowBullish, title='Rising Window – Bullish', message='New Rising Window – Bullish pattern detected')
if C_RisingWindowBullish and RisingWindowInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishRisingWindow = 'Rising Window\nBullish continuation 75%. Rising Window is a two-candle bullish continuation pattern that forms during an uptrend. Both candles in the pattern can be of any type with the exception of the Four-Price Doji. The most important characteristic of the pattern is a price gap between the first candle\'s high and the second candle\'s low. That gap (window) between two bars signifies support against the selling pressure.'
    label.new(bar_index, patternLabelPosLow, text='RW', style=label.style_label_up, color=label_color_bullcont, textcolor=color.white, tooltip=ttBullishRisingWindow)
C_FallingWindowBearishNumberOfCandles = 2
C_FallingWindowBearish = false
if C_DownTrend[1] and C_Range != 0 and C_Range[1] != 0 and high < low[1]
    C_FallingWindowBearish := true
    C_FallingWindowBearish
alertcondition(C_FallingWindowBearish, title='Falling Window – Bearish', message='New Falling Window – Bearish pattern detected')
if C_FallingWindowBearish and FallingWindowInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishFallingWindow = 'Falling Window\nBearish continuation 67%. Falling Window is a two-candle bearish continuation pattern that forms during a downtrend. Both candles in the pattern can be of any type, with the exception of the Four-Price Doji. The most important characteristic of the pattern is a price gap between the first candle\'s low and the second candle\'s high. The existence of this gap (window) means that the bearish trend is expected to continue.'
    label.new(bar_index, patternLabelPosHigh, text='FW', style=label.style_label_down, color=label_color_bearcont, textcolor=color.white, tooltip=ttBearishFallingWindow)
C_FallingThreeMethodsBearishNumberOfCandles = 5
C_FallingThreeMethodsBearish = false
if C_DownTrend[4] and C_LongBody[4] and C_BlackBody[4] and C_SmallBody[3] and C_WhiteBody[3] and open[3] > low[4] and close[3] < high[4] and C_SmallBody[2] and C_WhiteBody[2] and open[2] > low[4] and close[2] < high[4] and C_SmallBody[1] and C_WhiteBody[1] and open[1] > low[4] and close[1] < high[4] and C_LongBody and C_BlackBody and close < close[4]
    C_FallingThreeMethodsBearish := true
    C_FallingThreeMethodsBearish
alertcondition(C_FallingThreeMethodsBearish, title='Falling Three Methods – Bearish', message='New Falling Three Methods – Bearish pattern detected')
if C_FallingThreeMethodsBearish and FallingThreeMethodsInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishFallingThreeMethods = 'Falling Three Methods\nBearish continuation 71%. Falling Three Methods is a five-candle bearish pattern that signifies a continuation of an existing downtrend. The first candle is long and red, followed by three short green candles with bodies inside the range of the first candle. The last candle is also red and long and it closes below the close of the first candle. This decisive fifth strongly bearish candle hints that bulls could not reverse the prior downtrend and that bears have regained control of the market.'
    label.new(bar_index, patternLabelPosHigh, text='FTM', style=label.style_label_down, color=label_color_bearcont, textcolor=color.white, tooltip=ttBearishFallingThreeMethods)
C_RisingThreeMethodsBullishNumberOfCandles = 5
C_RisingThreeMethodsBullish = false
if C_UpTrend[4] and C_LongBody[4] and C_WhiteBody[4] and C_SmallBody[3] and C_BlackBody[3] and open[3] < high[4] and close[3] > low[4] and C_SmallBody[2] and C_BlackBody[2] and open[2] < high[4] and close[2] > low[4] and C_SmallBody[1] and C_BlackBody[1] and open[1] < high[4] and close[1] > low[4] and C_LongBody and C_WhiteBody and close > close[4]
    C_RisingThreeMethodsBullish := true
    C_RisingThreeMethodsBullish
alertcondition(C_RisingThreeMethodsBullish, title='Rising Three Methods – Bullish', message='New Rising Three Methods – Bullish pattern detected')
if C_RisingThreeMethodsBullish and RisingThreeMethodsInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishRisingThreeMethods = 'Rising Three Methods\nBullish continuation 74%. Rising Three Methods is a five-candle bullish pattern that signifies a continuation of an existing uptrend. The first candle is long and green, followed by three short red candles with bodies inside the range of the first candle. The last candle is also green and long and it closes above the close of the first candle. This decisive fifth strongly bullish candle hints that bears could not reverse the prior uptrend and that bulls have regained control of the market.'
    label.new(bar_index, patternLabelPosLow, text='RTM', style=label.style_label_up, color=label_color_bullcont, textcolor=color.white, tooltip=ttBullishRisingThreeMethods)


C_TweezerTopBearishNumberOfCandles = 2
C_TweezerTopBearish = false
if C_UpTrend[1] and (not C_IsDojiBody or C_HasUpShadow and C_HasDnShadow) and math.abs(high - high[1]) <= C_BodyAvg * 0.05 and C_WhiteBody[1] and C_BlackBody and C_LongBody[1]
    C_TweezerTopBearish := true
    C_TweezerTopBearish
alertcondition(C_TweezerTopBearish, title='Tweezer Top – Bearish', message='New Tweezer Top – Bearish pattern detected')
if C_TweezerTopBearish and TweezerTopInput and ('Bearish' == CandleType or CandleType == 'Both')

    //var ttBearishTweezerTop = 'Tweezer Top\nTested performance: Bullish continuation 56%. Theoretical performance: Bearish reversal. Tweezer Top is a two-candle pattern that signifies a potential bearish reversal. The pattern is found during an uptrend. The first candle is long and green, the second candle is red, and its high is nearly identical to the high of the previous candle. The virtually identical highs, together with the inverted directions, hint that bears might be taking over the market.'
    var ttBearishTweezerTop = 'Tweezer Top\n56%の確率で上げを継続。上昇トレンドの中によく現れる。'
    label.new(bar_index, patternLabelPosHigh, text='TT', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttBearishTweezerTop)
C_TweezerBottomBullishNumberOfCandles = 2
C_TweezerBottomBullish = false
if C_UpTrend[1] and (not C_IsDojiBody or C_HasUpShadow and C_HasDnShadow) and math.abs(low - low[1]) <= C_BodyAvg * 0.05 and C_BlackBody[1] and C_WhiteBody and C_LongBody[1]
    C_TweezerBottomBullish := true
    C_TweezerBottomBullish
alertcondition(C_TweezerBottomBullish, title='Tweezer Bottom – Bullish', message='New Tweezer Bottom – Bullish pattern detected')
if C_TweezerBottomBullish and TweezerBottomInput and ('Bullish' == CandleType or CandleType == 'Both')

    //var ttBullishTweezerBottom = 'Tweezer Bottom\nTested performance: Bearish continuation 52% of the time. Theoretical performance: Bullish reversal. Tweezer Bottom is a two-candle pattern that signifies a potential bullish reversal. The pattern is found during a downtrend. The first candle is long and red, the second candle is green, its lows nearly identical to the low of the previous candle. The virtually identical lows together with the inverted directions hint that bulls might be taking over the market.'
    var ttBullishTweezerBottom = 'Tweezer Bottom\n52%の確率で下げを継続。下降トレンドの中によく現れる。'
    label.new(bar_index, patternLabelPosHigh, text='TB', style=label.style_label_up, color=label_color_bearcont, textcolor=color.white, tooltip=ttBullishTweezerBottom)


C_DarkCloudCoverBearishNumberOfCandles = 2
C_DarkCloudCoverBearish = false
if C_UpTrend[1] and C_WhiteBody[1] and C_LongBody[1] and C_BlackBody and open >= high[1] and close < C_BodyMiddle[1] and close > open[1]
    C_DarkCloudCoverBearish := true
    C_DarkCloudCoverBearish
alertcondition(C_DarkCloudCoverBearish, title='Dark Cloud Cover – Bearish', message='New Dark Cloud Cover – Bearish pattern detected')
if C_DarkCloudCoverBearish and DarkCloudCoverInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishDarkCloudCover = 'Dark Cloud Cover\nBearish reversal 60% of the time. Dark Cloud Cover is a two-candle bearish reversal candlestick pattern found in an uptrend. The first candle is green and has a larger than average body. The second candle is red and opens above the high of the prior candle, creating a gap, and then closes below the midpoint of the first candle. The pattern shows a possible shift in the momentum from the upside to the downside, indicating that a reversal might happen soon.'
    label.new(bar_index, patternLabelPosHigh, text='DCC', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishDarkCloudCover)
C_DownsideTasukiGapBearishNumberOfCandles = 3
C_DownsideTasukiGapBearish = false
if C_LongBody[2] and C_SmallBody[1] and C_DownTrend and C_BlackBody[2] and C_BodyHi[1] < C_BodyLo[2] and C_BlackBody[1] and C_WhiteBody and C_BodyHi <= C_BodyLo[2] and C_BodyHi >= C_BodyHi[1]
    C_DownsideTasukiGapBearish := true
    C_DownsideTasukiGapBearish
alertcondition(C_DownsideTasukiGapBearish, title='Downside Tasuki Gap – Bearish', message='New Downside Tasuki Gap – Bearish pattern detected')
if C_DownsideTasukiGapBearish and DownsideTasukiGapInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishDownsideTasukiGap = 'Downside Tasuki Gap\nTested performance: Bullish reversal 54% of the time. Theoretical performance: Bearish continuation. Downside Tasuki Gap is a three-candle pattern found in a downtrend that usually hints at the continuation of the downtrend. The first candle is long and red, followed by a smaller red candle with its opening price that gaps below the body of the previous candle. The third candle is green and it closes inside the gap created by the first two candles, unable to close it fully. The bull’s inability to close that gap hints that the downtrend might continue.'
    label.new(bar_index, patternLabelPosHigh, text='DTG', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBearishDownsideTasukiGap)
C_UpsideTasukiGapBullishNumberOfCandles = 3
C_UpsideTasukiGapBullish = false
if C_LongBody[2] and C_SmallBody[1] and C_UpTrend and C_WhiteBody[2] and C_BodyLo[1] > C_BodyHi[2] and C_WhiteBody[1] and C_BlackBody and C_BodyLo >= C_BodyHi[2] and C_BodyLo <= C_BodyLo[1]
    C_UpsideTasukiGapBullish := true
    C_UpsideTasukiGapBullish
alertcondition(C_UpsideTasukiGapBullish, title='Upside Tasuki Gap – Bullish', message='New Upside Tasuki Gap – Bullish pattern detected')
if C_UpsideTasukiGapBullish and UpsideTasukiGapInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishUpsideTasukiGap = 'Upside Tasuki Gap\nBullish continuation 57% of the time. Upside Tasuki Gap is a three-candle pattern found in an uptrend that usually hints at the continuation of the uptrend. The first candle is long and green, followed by a smaller green candle with its opening price that gaps above the body of the previous candle. The third candle is red and it closes inside the gap created by the first two candles, unable to close it fully. The bear’s inability to close the gap hints that the uptrend might continue.'
    label.new(bar_index, patternLabelPosLow, text='UTG', style=label.style_label_up, color=label_color_bullcont, textcolor=color.white, tooltip=ttBullishUpsideTasukiGap)
C_EveningDojiStarBearishNumberOfCandles = 3
C_EveningDojiStarBearish = false
if C_LongBody[2] and C_IsDojiBody[1] and C_LongBody and C_UpTrend and C_WhiteBody[2] and C_BodyLo[1] > C_BodyHi[2] and C_BlackBody and C_BodyLo <= C_BodyMiddle[2] and C_BodyLo > C_BodyLo[2] and C_BodyLo[1] > C_BodyHi
    C_EveningDojiStarBearish := true
    C_EveningDojiStarBearish
alertcondition(C_EveningDojiStarBearish, title='Evening Doji Star – Bearish', message='New Evening Doji Star – Bearish pattern detected')
if C_EveningDojiStarBearish and EveningDojiStarInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishEveningDojiStar = 'Evening Doji Star\nBearish reversal 71% of the time. This candlestick pattern is a variation of the Evening Star pattern. It is bearish and continues an uptrend with a long-bodied, green candle day. It is then followed by a gap and a Doji candle and concludes with a downward close. The close would be below the first day’s midpoint. It is more bearish than the regular evening star pattern because of the existence of the Doji.'
    label.new(bar_index, patternLabelPosHigh, text='EDS', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishEveningDojiStar)
C_DojiStarBearishNumberOfCandles = 2
C_DojiStarBearish = false
if C_UpTrend and C_WhiteBody[1] and C_LongBody[1] and C_IsDojiBody and C_BodyLo > C_BodyHi[1]
    C_DojiStarBearish := true
    C_DojiStarBearish
alertcondition(C_DojiStarBearish, title='Doji Star – Bearish', message='New Doji Star – Bearish pattern detected')
if C_DojiStarBearish and DojiStarInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishDojiStar = 'Doji Star\nTested performance: Bullish continuation 69% of the time. Theoretical performance: Bearish reversal. This is a bearish reversal candlestick pattern that is found in an uptrend and consists of two candles. First comes a long green candle, followed by a Doji candle (except 4-Price Doji) that opens above the body of the first one, creating a gap. It is considered a reversal signal with confirmation during the next trading day.'
    label.new(bar_index, patternLabelPosHigh, text='DS', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttBearishDojiStar)
C_DojiStarBullishNumberOfCandles = 2
C_DojiStarBullish = false
if C_DownTrend and C_BlackBody[1] and C_LongBody[1] and C_IsDojiBody and C_BodyHi < C_BodyLo[1]
    C_DojiStarBullish := true
    C_DojiStarBullish
alertcondition(C_DojiStarBullish, title='Doji Star – Bullish', message='New Doji Star – Bullish pattern detected')
if C_DojiStarBullish and DojiStarInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishDojiStar = 'Doji Star\nTested performance: Bearish continuation 64% of the time. Theoretical performance: Bullish reversal. This is a bullish reversal candlestick pattern that is found in a downtrend and consists of two candles. First comes a long red candle, followed by a Doji candle (except 4-Price Doji) that opens below the body of the first one, creating a gap. It is considered a reversal signal with confirmation during the next trading day.'
    label.new(bar_index, patternLabelPosLow, text='DS', style=label.style_label_up, color=label_color_bearcont, textcolor=color.white, tooltip=ttBullishDojiStar)
C_MorningDojiStarBullishNumberOfCandles = 3
C_MorningDojiStarBullish = false
if C_LongBody[2] and C_IsDojiBody[1] and C_LongBody and C_DownTrend and C_BlackBody[2] and C_BodyHi[1] < C_BodyLo[2] and C_WhiteBody and C_BodyHi >= C_BodyMiddle[2] and C_BodyHi < C_BodyHi[2] and C_BodyHi[1] < C_BodyLo
    C_MorningDojiStarBullish := true
    C_MorningDojiStarBullish
alertcondition(C_MorningDojiStarBullish, title='Morning Doji Star – Bullish', message='New Morning Doji Star – Bullish pattern detected')
if C_MorningDojiStarBullish and MorningDojiStarInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishMorningDojiStar = 'Morning Doji Star\nBullish reversal 76% of the time. This candlestick pattern is a variation of the Morning Star pattern. A three-day bullish reversal pattern, which consists of three candlesticks will look something like this: The first being a long-bodied red candle that extends the current downtrend. Next comes a Doji that gaps down on the open. After that comes a long-bodied green candle, which gaps up on the open and closes above the midpoint of the body of the first day. It is more bullish than the regular morning star pattern because of the existence of the Doji.'
    label.new(bar_index, patternLabelPosLow, text='MDS', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishMorningDojiStar)
C_PiercingBullishNumberOfCandles = 2
C_PiercingBullish = false
if C_DownTrend[1] and C_BlackBody[1] and C_LongBody[1] and C_WhiteBody and open <= low[1] and close > C_BodyMiddle[1] and close < open[1]
    C_PiercingBullish := true
    C_PiercingBullish
alertcondition(C_PiercingBullish, title='Piercing – Bullish', message='New Piercing – Bullish pattern detected')
if C_PiercingBullish and PiercingInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishPiercing = 'Piercing\nBullish reversal 64% of the time. Piercing is a two-candle bullish reversal candlestick pattern found in a downtrend. The first candle is red and has a larger than average body. The second candle is green and opens below the low of the prior candle, creating a gap, and then closes above the midpoint of the first candle. The pattern shows a possible shift in the momentum from the downside to the upside, indicating that a reversal might happen soon.'
    label.new(bar_index, patternLabelPosLow, text='P', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishPiercing)
C_HammerBullishNumberOfCandles = 1
C_HammerBullish = false
if C_SmallBody and C_Body > 0 and C_BodyLo > hl2 and C_DnShadow >= C_Factor * C_Body and not C_HasUpShadow
    if C_DownTrend
        C_HammerBullish := true
        C_HammerBullish
alertcondition(C_HammerBullish, title='Hammer – Bullish', message='New Hammer – Bullish pattern detected')
if C_HammerBullish and HammerInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishHammer = 'Hammer\nBullish reversal 60% of the time. Hammer candlesticks form when a security moves lower after the open, but continues to rally into close above the intraday low. The candlestick that you are left with will look like a square attached to a long stick-like figure. This candlestick is called a Hammer if it happens to form during a decline.'
    label.new(bar_index, patternLabelPosLow, text='H', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishHammer)
C_HangingManBearishNumberOfCandles = 1
C_HangingManBearish = false
if C_SmallBody and C_Body > 0 and C_BodyLo > hl2 and C_DnShadow >= C_Factor * C_Body and not C_HasUpShadow
    if C_UpTrend
        C_HangingManBearish := true
        C_HangingManBearish
alertcondition(C_HangingManBearish, title='Hanging Man – Bearish', message='New Hanging Man – Bearish pattern detected')
if C_HangingManBearish and HangingManInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishHangingMan = 'Hanging Man\nTested performance: Bullish continuation 59% of the time. Theoretical performance: Bearish reversal. When a specified security notably moves lower after the open, but continues to rally to close above the intraday low, a Hanging Man candlestick will form. The candlestick will resemble a square, attached to a long stick-like figure. It is referred to as a Hanging Man if the candlestick forms during an advance.'
    label.new(bar_index, patternLabelPosHigh, text='HM', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttBearishHangingMan)
C_ShootingStarBearishNumberOfCandles = 1
C_ShootingStarBearish = false
if C_SmallBody and C_Body > 0 and C_BodyHi < hl2 and C_UpShadow >= C_Factor * C_Body and not C_HasDnShadow
    if C_UpTrend
        C_ShootingStarBearish := true
        C_ShootingStarBearish
alertcondition(C_ShootingStarBearish, title='Shooting Star – Bearish', message='New Shooting Star – Bearish pattern detected')
if C_ShootingStarBearish and ShootingStarInput and ('Bearish' == CandleType or CandleType == 'Both')

   // var ttBearishShootingStar = 'Shooting Star\nBearish reversal 59% of the time. This single day pattern can appear during an uptrend and opens high, while it closes near its open. It trades much higher as well. It is bearish in nature, but looks like an Inverted Hammer.'
    var ttBearishShootingStar = 'Shooting Star\n59％の確率で下げに反転。上昇トレンド中に現れること多め。'
    label.new(bar_index, patternLabelPosHigh, text='SS', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishShootingStar)
C_Inverted_HammerBullishNumberOfCandles = 1
C_Inverted_HammerBullish = false
if C_SmallBody and C_Body > 0 and C_BodyHi < hl2 and C_UpShadow >= C_Factor * C_Body and not C_HasDnShadow
    if C_DownTrend
        C_Inverted_HammerBullish := true
        C_Inverted_HammerBullish
alertcondition(C_Inverted_HammerBullish, title='Inverted Hammer – Bullish', message='New Inverted Hammer – Bullish pattern detected')
if C_Inverted_HammerBullish and Inverted_HammerInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishInverted_Hammer = 'Inverted Hammer\nTested performance: Bearish continuation 65% of the time. Theoretical performance: Bullish reversal. If in a downtrend, then the open is lower. When it eventually trades higher, but closes near its open, it will look like an inverted version of the Hammer Candlestick. This is a one-day bullish reversal pattern.'
    label.new(bar_index, patternLabelPosLow, text='IH', style=label.style_label_down, color=label_color_bearcont, textcolor=color.white, tooltip=ttBullishInverted_Hammer)
C_MorningStarBullishNumberOfCandles = 3
C_MorningStarBullish = false
if C_LongBody[2] and C_SmallBody[1] and C_LongBody
    if C_DownTrend and C_BlackBody[2] and C_BodyHi[1] < C_BodyLo[2] and C_WhiteBody and C_BodyHi >= C_BodyMiddle[2] and C_BodyHi < C_BodyHi[2] and C_BodyHi[1] < C_BodyLo
        C_MorningStarBullish := true
        C_MorningStarBullish
alertcondition(C_MorningStarBullish, title='Morning Star – Bullish', message='New Morning Star – Bullish pattern detected')
if C_MorningStarBullish and MorningStarInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishMorningStar = 'Morning Star\nBullish reversal 78% of the time. A three-day bullish reversal pattern, which consists of three candlesticks will look something like this: The first being a long-bodied red candle that extends the current downtrend. Next comes a short, middle candle that gaps down on the open. After comes a long-bodied green candle, which gaps up on the open and closes above the midpoint of the body of the first day.'
    label.new(bar_index, patternLabelPosLow, text='MS', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishMorningStar)
C_EveningStarBearishNumberOfCandles = 3
C_EveningStarBearish = false
if C_LongBody[2] and C_SmallBody[1] and C_LongBody
    if C_UpTrend and C_WhiteBody[2] and C_BodyLo[1] > C_BodyHi[2] and C_BlackBody and C_BodyLo <= C_BodyMiddle[2] and C_BodyLo > C_BodyLo[2] and C_BodyLo[1] > C_BodyHi
        C_EveningStarBearish := true
        C_EveningStarBearish
alertcondition(C_EveningStarBearish, title='Evening Star – Bearish', message='New Evening Star – Bearish pattern detected')
if C_EveningStarBearish and EveningStarInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishEveningStar = 'Evening Star\nBearish reversal 72% of the time. This candlestick pattern is bearish and continues an uptrend with a long-bodied, green candle day. It is then followed by a gapped and small-bodied candle day, and concludes with a downward close. The close would be below the first day’s midpoint.'
    label.new(bar_index, patternLabelPosHigh, text='ES', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishEveningStar)

C_MarubozuWhiteBullishNumberOfCandles = 1
C_MarubozuShadowPercentWhite = 5.0
C_MarubozuWhiteBullish = C_WhiteBody and C_LongBody and C_UpShadow <= C_MarubozuShadowPercentWhite/100*C_Body and C_DnShadow <= C_MarubozuShadowPercentWhite/100*C_Body and C_WhiteBody
alertcondition(C_MarubozuWhiteBullish, title = "Marubozu White – Bullish", message = "New Marubozu White – Bullish pattern detected")
if C_MarubozuWhiteBullish  and  MarubozuWhiteInput and (("Bullish" == CandleType) or CandleType == "Both")

   // var ttBullishMarubozuWhite = "Marubozu White\nContinuation 54-56% of the time. A Marubozu White Candle is a candlestick that does not have a shadow that extends from its candle body at either the open or the close. Marubozu is Japanese for “close-cropped” or “close-cut.” Other sources may call it a Bald or Shaven Head Candle."
    var ttBullishMarubozuWhite = "Marubozu White\n54-56%の確率でトレンド、ないし同じローソク足が継続する"
    label.new(bar_index, patternLabelPosLow, text="MW", style=label.style_label_up, color = label_color_bullcont, textcolor=color.white, tooltip = ttBullishMarubozuWhite)

C_MarubozuBlackBearishNumberOfCandles = 1
C_MarubozuShadowPercentBearish = 5.0
C_MarubozuBlackBearish = C_BlackBody and C_LongBody and C_UpShadow <= C_MarubozuShadowPercentBearish/100*C_Body and C_DnShadow <= C_MarubozuShadowPercentBearish/100*C_Body and C_BlackBody
alertcondition(C_MarubozuBlackBearish, title = "Marubozu Black – Bearish", message = "New Marubozu Black – Bearish pattern detected")
if C_MarubozuBlackBearish  and  MarubozuBlackInput and (("Bearish" == CandleType) or CandleType == "Both")

    //var ttBearishMarubozuBlack = "Marubozu Black\nContinuation 53% of the time. This is a candlestick that has no shadow, which extends from the red-bodied candle at the open, the close, or even at both. In Japanese, the name means “close-cropped” or “close-cut.” The candlestick can also be referred to as Bald or Shaven Head."
    var ttBearishMarubozuBlack = "Marubozu Black\n53%の確率でトレンド、ないし同じローソク足が継続する"
    label.new(bar_index, patternLabelPosHigh, text="MB", style=label.style_label_down, color = label_color_neutral, textcolor=color.white, tooltip = ttBearishMarubozuBlack)


C_DojiNumberOfCandles = 1
C_DragonflyDoji = C_IsDojiBody and C_UpShadow <= C_Body
C_GravestoneDojiOne = C_IsDojiBody and C_DnShadow <= C_Body
alertcondition(C_Doji and not C_DragonflyDoji and not C_GravestoneDojiOne, title='Doji', message='New Doji pattern detected')
if C_Doji and not C_DragonflyDoji and not C_GravestoneDojiOne and DojiInput
   // var ttDoji = 'Doji\nIndecision. Bullish continuation 51% of the time. When the open and close of a security are essentially equal to each other, a doji candle forms. The length of both upper and lower shadows may vary, causing the candlestick you are left with to either resemble a cross, an inverted cross, or a plus sign. Doji candles show the playout of buyer-seller indecision in a tug-of-war of sorts. As price moves either above or below the opening level during the session, the close is either at or near the opening level.'
    var ttDoji = 'Doji\n上げへの反転が51%。優柔不断。どっちに転ぶかわからない'
    label.new(bar_index, patternLabelPosLow, text='D', style=label.style_label_up, color=label_color_bullcont, textcolor=color.white, tooltip=ttDoji)
C_GravestoneDojiBearishNumberOfCandles = 1
C_GravestoneDojiBearish = C_IsDojiBody and C_DnShadow <= C_Body
alertcondition(C_GravestoneDojiBearish, title='Gravestone Doji – Bearish', message='New Gravestone Doji – Bearish pattern detected')
if C_GravestoneDojiBearish and GravestoneDojiInput and ('Bearish' == CandleType or CandleType == 'Both')

   // var ttBearishGravestoneDoji = 'Gravestone Doji\nIndecision to Bearish reversal 51% of the time. When a doji is at or is close to the day’s low point, a doji line will develop.'
    var ttBearishGravestoneDoji = 'Gravestone Doji\n下げへの反転が51%。優柔不断。どっちに転ぶかわからない'
    label.new(bar_index, patternLabelPosHigh, text='GD', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishGravestoneDoji)

C_DragonflyDojiBullishNumberOfCandles = 1
C_DragonflyDojiBullish = C_IsDojiBody and C_UpShadow <= C_Body
alertcondition(C_DragonflyDojiBullish, title='Dragonfly Doji – Bullish', message='New Dragonfly Doji – Bullish pattern detected')
if C_DragonflyDojiBullish and DragonflyDojiInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishDragonflyDoji = 'Dragonfly Doji\nBullish reversal 50% during a decline, otherwise indecision. Similar to other Doji days, this particular Doji also regularly appears at pivotal market moments. This is a specific Doji where both the open and close price are at the high of a given day.'
    label.new(bar_index, patternLabelPosLow, text='DD', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishDragonflyDoji)
C_HaramiCrossBullishNumberOfCandles = 2
C_HaramiCrossBullish = C_LongBody[1] and C_BlackBody[1] and C_DownTrend[1] and C_IsDojiBody and high <= C_BodyHi[1] and low >= C_BodyLo[1]
alertcondition(C_HaramiCrossBullish, title='Harami Cross – Bullish', message='New Harami Cross – Bullish pattern detected')
if C_HaramiCrossBullish and HaramiCrossInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishHaramiCross = 'Harami Cross\nBearish continuation 55% of the time. Theoretical performance: Bullish reversal. This candlestick pattern is a variation of the Harami Bullish pattern. It is found during a downtrend. The two-day candlestick pattern consists of a Doji candle that is entirely encompassed within the body of what was once a red-bodied candle.'
    label.new(bar_index, patternLabelPosLow, text='HC', style=label.style_label_up, color=label_color_bearcont, textcolor=color.white, tooltip=ttBullishHaramiCross)
C_HaramiCrossBearishNumberOfCandles = 2
C_HaramiCrossBearish = C_LongBody[1] and C_WhiteBody[1] and C_UpTrend[1] and C_IsDojiBody and high <= C_BodyHi[1] and low >= C_BodyLo[1]
alertcondition(C_HaramiCrossBearish, title='Harami Cross – Bearish', message='New Harami Cross – Bearish pattern detected')
if C_HaramiCrossBearish and HaramiCrossInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishHaramiCross = 'Harami Cross\nBullish continuation 57% of the time. Theoretical performance: Bearish reversal. This candlestick pattern is a variation of the Harami Bearish pattern. It is found during an uptrend. This is a two-day candlestick pattern with a Doji candle that is entirely encompassed within the body that was once a green-bodied candle. The Doji shows that some indecision has entered the minds of sellers, and the pattern hints that the trend might reverse.'
    label.new(bar_index, patternLabelPosHigh, text='HC', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttBearishHaramiCross)
C_HaramiBullishNumberOfCandles = 2
C_HaramiBullish = C_LongBody[1] and C_BlackBody[1] and C_DownTrend[1] and C_WhiteBody and C_SmallBody and high <= C_BodyHi[1] and low >= C_BodyLo[1]
alertcondition(C_HaramiBullish, title='Harami – Bullish', message='New Harami – Bullish pattern detected')
if C_HaramiBullish and HaramiInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishHarami = 'Harami\nBullish reversal 53% of the time. This two-day candlestick pattern consists of a small-bodied green candle that is entirely encompassed within the body of what was once a red-bodied candle.'
    label.new(bar_index, patternLabelPosLow, text='BH', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishHarami)
C_HaramiBearishNumberOfCandles = 2
C_HaramiBearish = C_LongBody[1] and C_WhiteBody[1] and C_UpTrend[1] and C_BlackBody and C_SmallBody and high <= C_BodyHi[1] and low >= C_BodyLo[1]
alertcondition(C_HaramiBearish, title='Harami – Bearish', message='New Harami – Bearish pattern detected')
if C_HaramiBearish and HaramiInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishHarami = 'Harami\nBullish continuation 53% of the time. Theoretical performance: Bearish reversal. This is a two-day candlestick pattern with a small, red-bodied candle that is entirely encompassed within the body that was once a green-bodied candle.'
    label.new(bar_index, patternLabelPosHigh, text='BH', style=label.style_label_down, color=label_color_bullcont, textcolor=color.white, tooltip=ttBearishHarami)

// C_LongLowerShadowBullishNumberOfCandles = 1
// C_LongLowerShadowPercent = 75.0
// C_LongLowerShadowBullish = C_DnShadow > C_Range/100*C_LongLowerShadowPercent
// alertcondition(C_LongLowerShadowBullish, title = "Long Lower Shadow – Bullish", message = "New Long Lower Shadow – Bullish pattern detected")
// if C_LongLowerShadowBullish  and  LongLowerShadowInput and (("Bullish" == CandleType) or CandleType == "Both")

//     var ttBullishLongLowerShadow = "Long Lower Shadow\nConsidered to be a weak bullish signal. In addition, when the market is oversold or at support, the Long Lower Shadow candlestick tends to be more significant.To indicate seller domination of the first part of a session, candlesticks will present with long lower shadows and short upper shadows, consequently lowering prices."
//     label.new(bar_index, patternLabelPosLow, text="LLS", style=label.style_label_up, color = label_color_bullish, textcolor=color.white, tooltip = ttBullishLongLowerShadow)

// C_LongUpperShadowBearishNumberOfCandles = 1
// C_LongShadowPercent = 75.0
// C_LongUpperShadowBearish = C_UpShadow > C_Range/100*C_LongShadowPercent
// alertcondition(C_LongUpperShadowBearish, title = "Long Upper Shadow – Bearish", message = "New Long Upper Shadow – Bearish pattern detected")
// if C_LongUpperShadowBearish  and  LongUpperShadowInput and (("Bearish" == CandleType) or CandleType == "Both")

//     var ttBearishLongUpperShadow = "Long Upper Shadow\nIt is considered a weak bearish pattern and takes on greater significance when the market is over bought or at resistance. To indicate buyer domination of the first part of a session, candlesticks will present with long upper shadows, as well as short lower shadows, consequently raising bidding prices."
//     label.new(bar_index, patternLabelPosHigh, text="LUS", style=label.style_label_down, color = label_color_bearish, textcolor=color.white, tooltip = ttBearishLongUpperShadow)

C_SpinningTopWhiteNumberOfCandles = 1
C_SpinningTopWhitePercent = 34.0
C_IsSpinningTopWhite = C_DnShadow >= C_Range / 100 * C_SpinningTopWhitePercent and C_UpShadow >= C_Range / 100 * C_SpinningTopWhitePercent and not C_IsDojiBody
C_SpinningTopWhite = C_IsSpinningTopWhite and C_WhiteBody
alertcondition(C_SpinningTopWhite, title='Spinning Top White', message='New Spinning Top White pattern detected')
if C_SpinningTopWhite and SpinningTopWhiteInput
   // var ttSpinningTopWhite = 'Spinning Top White\nTested performance: Reversal 50% of the time. Theoretical performance: Indecision. White spinning tops are candlestick lines that are small, green-bodied, and possess shadows (upper and lower) that end up exceeding the length of candle bodies. They often signal indecision between buyer and seller.'
    var ttSpinningTopWhite = 'Spinning Top White\n反転する確率50%。優柔不断の信号、どっちに転ぶかわからない'
    label.new(bar_index, patternLabelPosLow, text='STW', style=label.style_label_up, color=label_color_neutral, textcolor=color.white, tooltip=ttSpinningTopWhite)

C_SpinningTopBlackNumberOfCandles = 1
C_SpinningTopBlackPercent = 34.0
C_IsSpinningTop = C_DnShadow >= C_Range / 100 * C_SpinningTopBlackPercent and C_UpShadow >= C_Range / 100 * C_SpinningTopBlackPercent and not C_IsDojiBody
C_SpinningTopBlack = C_IsSpinningTop and C_BlackBody
alertcondition(C_SpinningTopBlack, title='Spinning Top Black', message='New Spinning Top Black pattern detected')
if C_SpinningTopBlack and SpinningTopBlackInput
    //var ttSpinningTopBlack = 'Spinning Top Black\nTested performance: Reversal 51% of the time. Theoretical performance: Indecision. Black spinning tops are candlestick lines that are small, red-bodied, and possess shadows (upper and lower) that end up exceeding the length of candle bodies. They often signal indecision.'
    var ttSpinningTopBlack = 'Spinning Top Black\n反転する確率51%。優柔不断の信号、どっちに転ぶかわからない'
    label.new(bar_index, patternLabelPosLow, text='STB', style=label.style_label_up, color=label_color_neutral, textcolor=color.white, tooltip=ttSpinningTopBlack)

C_ThreeWhiteSoldiersBullishNumberOfCandles = 3
C_3WSld_ShadowPercent = 5.0
C_3WSld_HaveNotUpShadow = C_Range * C_3WSld_ShadowPercent / 100 > C_UpShadow
C_ThreeWhiteSoldiersBullish = false
if C_LongBody and C_LongBody[1] and C_LongBody[2]
    if C_WhiteBody and C_WhiteBody[1] and C_WhiteBody[2]
        C_ThreeWhiteSoldiersBullish := close > close[1] and close[1] > close[2] and open < close[1] and open > open[1] and open[1] < close[2] and open[1] > open[2] and C_3WSld_HaveNotUpShadow and C_3WSld_HaveNotUpShadow[1] and C_3WSld_HaveNotUpShadow[2]
        C_ThreeWhiteSoldiersBullish
alertcondition(C_ThreeWhiteSoldiersBullish, title='Three White Soldiers – Bullish', message='New Three White Soldiers – Bullish pattern detected')
if C_ThreeWhiteSoldiersBullish and ThreeWhiteSoldiersInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishThreeWhiteSoldiers = 'Three White Soldiers\n**Bullish reversal 82% of the time. This bullish reversal pattern is made up of three long-bodied, green candles in immediate succession. Each one opens within the body before it and the close is near to the daily high.'
    label.new(bar_index, patternLabelPosLow, text='3WS', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishThreeWhiteSoldiers)
C_ThreeBlackCrowsBearishNumberOfCandles = 3
C_3BCrw_ShadowPercent = 5.0
C_3BCrw_HaveNotDnShadow = C_Range * C_3BCrw_ShadowPercent / 100 > C_DnShadow
C_ThreeBlackCrowsBearish = false
if C_LongBody and C_LongBody[1] and C_LongBody[2]
    if C_BlackBody and C_BlackBody[1] and C_BlackBody[2]
        C_ThreeBlackCrowsBearish := close < close[1] and close[1] < close[2] and open > close[1] and open < open[1] and open[1] > close[2] and open[1] < open[2] and C_3BCrw_HaveNotDnShadow and C_3BCrw_HaveNotDnShadow[1] and C_3BCrw_HaveNotDnShadow[2]
        C_ThreeBlackCrowsBearish
alertcondition(C_ThreeBlackCrowsBearish, title='Three Black Crows – Bearish', message='New Three Black Crows – Bearish pattern detected')
if C_ThreeBlackCrowsBearish and ThreeBlackCrowsInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishThreeBlackCrows = 'Three Black Crows\n**Bearish reversal 78% of the time. Overall performance rank: 3. This is a bearish reversal pattern that consists of three long, red-bodied candles in immediate succession. For each of these candles, each day opens within the body of the day before and closes either at or near its low.'
    label.new(bar_index, patternLabelPosHigh, text='3BC', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishThreeBlackCrows)


C_EngulfingBullishNumberOfCandles = 2
C_EngulfingBullish = C_DownTrend and C_WhiteBody and C_LongBody and C_BlackBody[1] and C_SmallBody[1] and close >= open[1] and open <= close[1] and (close > open[1] or open < close[1])
alertcondition(C_EngulfingBullish, title='Engulfing – Bullish', message='New Engulfing – Bullish pattern detected')
if C_EngulfingBullish and EngulfingInput and ('Bullish' == CandleType or CandleType == 'Both')

   // var ttBullishEngulfing = 'Engulfing\n**Bullish reversal 63% of the time. At the end of a given downward trend, there will most likely be a reversal pattern. To distinguish the first day, this candlestick pattern uses a small body, followed by a day where the candle body fully overtakes the body from the day before, and closes in the trend’s opposite direction. Although similar to the outside reversal chart pattern, it is not essential for this pattern to completely overtake the range (high to low), rather only the open and the close.'
    var ttBullishEngulfing = 'Bullish Engulfing\n**63%の確率で上げに反転する。下降トレンドの終わりに出現すること多い。'
    label.new(bar_index, patternLabelPosLow, text='BE', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishEngulfing)
C_EngulfingBearishNumberOfCandles = 2
C_EngulfingBearish = C_UpTrend and C_BlackBody and C_LongBody and C_WhiteBody[1] and C_SmallBody[1] and close <= open[1] and open >= close[1] and (close < open[1] or open > close[1])
alertcondition(C_EngulfingBearish, title='Engulfing – Bearish', message='New Engulfing – Bearish pattern detected')
if C_EngulfingBearish and EngulfingInput and ('Bearish' == CandleType or CandleType == 'Both')

   // var ttBearishEngulfing = 'Engulfing\n**Bearish reversal 79% of the time. At the end of a given uptrend, a reversal pattern will most likely appear. During the first day, this candlestick pattern uses a small body. It is then followed by a day where the candle body fully overtakes the body from the day before it and closes in the trend’s opposite direction. Although similar to the outside reversal chart pattern, it is not essential for this pattern to fully overtake the range (high to low), rather only the open and the close.'
    var ttBearishEngulfing = '	Bearish Engulfing\n**79%の確率で下げに反転する。上昇トレンドの終わりに出現すること多い。'
    label.new(bar_index, patternLabelPosHigh, text='BE', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishEngulfing)


C_AbandonedBabyBullishNumberOfCandles = 3
C_AbandonedBabyBullish = C_DownTrend[2] and C_BlackBody[2] and C_IsDojiBody[1] and low[2] > high[1] and C_WhiteBody and high[1] < low
alertcondition(C_AbandonedBabyBullish, title='Abandoned Baby – Bullish', message='New Abandoned Baby – Bullish pattern detected')
if C_AbandonedBabyBullish and AbandonedBabyInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishAbandonedBaby = 'Abandoned Baby\n**Bullish reversal 70% of the time. Overall performance rank: 9. This candlestick pattern is quite rare as far as reversal patterns go. The first of the pattern is a large down candle. Next comes a doji candle that gaps below the candle before it. The doji candle is then followed by another candle that opens even higher and swiftly moves to the upside.'
    label.new(bar_index, patternLabelPosLow, text='AB', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishAbandonedBaby)
C_AbandonedBabyBearishNumberOfCandles = 3
C_AbandonedBabyBearish = C_UpTrend[2] and C_WhiteBody[2] and C_IsDojiBody[1] and high[2] < low[1] and C_BlackBody and low[1] > high
alertcondition(C_AbandonedBabyBearish, title='Abandoned Baby – Bearish', message='New Abandoned Baby – Bearish pattern detected')
if C_AbandonedBabyBearish and AbandonedBabyInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishAbandonedBaby = 'Abandoned Baby\n*Bearish reversal 69% of the time. A bearish abandoned baby is a specific candlestick pattern that often signals a downward reversal trend in terms of security price. It is formed when a gap appears between the lowest price of a doji-like candle and the candlestick of the day before. The earlier candlestick is green, tall, and has small shadows. The doji candle is also tailed by a gap between its lowest price point and the highest price point of the candle that comes next, which is red, tall and also has small shadows. The doji candle shadows must completely gap either below or above the shadows of the first and third day in order to have the abandoned baby pattern effect.'
    label.new(bar_index, patternLabelPosHigh, text='AB', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishAbandonedBaby)
C_TriStarBullishNumberOfCandles = 3
C_3DojisBullish = C_Doji[2] and C_Doji[1] and C_Doji
C_BodyGapUpBullish = C_BodyHi[1] < C_BodyLo
C_BodyGapDnBullish = C_BodyLo[1] > C_BodyHi
C_TriStarBullish = C_3DojisBullish and C_DownTrend[2] and C_BodyGapDnBullish[1] and C_BodyGapUpBullish
alertcondition(C_TriStarBullish, title='Tri-Star – Bullish', message='New Tri-Star – Bullish pattern detected')
if C_TriStarBullish and TriStarInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishTriStar = 'Tri-Star\nBullish reversal 60% of the time. A bullish TriStar candlestick pattern can form when three doji candlesticks materialize in immediate succession at the tail-end of an extended downtrend. The first doji candle marks indecision between bull and bear. The second doji gaps in the direction of the leading trend. The third changes the attitude of the market once the candlestick opens in the direction opposite to the trend. Each doji candle has a shadow, all comparatively shallow, which signify an interim cutback in volatility.'
    label.new(bar_index, patternLabelPosLow, text='3S', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishTriStar)
C_TriStarBearishNumberOfCandles = 3
C_3Dojis = C_Doji[2] and C_Doji[1] and C_Doji
C_BodyGapUp = C_BodyHi[1] < C_BodyLo
C_BodyGapDn = C_BodyLo[1] > C_BodyHi
C_TriStarBearish = C_3Dojis and C_UpTrend[2] and C_BodyGapUp[1] and C_BodyGapDn
alertcondition(C_TriStarBearish, title='Tri-Star – Bearish', message='New Tri-Star – Bearish pattern detected')
if C_TriStarBearish and TriStarInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishTriStar = 'Tri-Star\nBearish reversal 52%. This particular pattern can form when three doji candlesticks appear in immediate succession at the end of an extended uptrend. The first doji candle marks indecision between bull and bear. The second doji gaps in the direction of the leading trend. The third changes the attitude of the market once the candlestick opens in the direction opposite to the trend. Each doji candle has a shadow, all comparatively shallow, which signify an interim cutback in volatility.'
    label.new(bar_index, patternLabelPosHigh, text='3S', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishTriStar)
C_KickingBullishNumberOfCandles = 2
C_MarubozuShadowPercent = 5.0
C_Marubozu = C_LongBody and C_UpShadow <= C_MarubozuShadowPercent / 100 * C_Body and C_DnShadow <= C_MarubozuShadowPercent / 100 * C_Body
C_MarubozuWhiteBullishKicking = C_Marubozu and C_WhiteBody
C_MarubozuBlackBullish = C_Marubozu and C_BlackBody
C_KickingBullish = C_MarubozuBlackBullish[1] and C_MarubozuWhiteBullishKicking and high[1] < low
alertcondition(C_KickingBullish, title='Kicking – Bullish', message='New Kicking – Bullish pattern detected')
if C_KickingBullish and KickingInput and ('Bullish' == CandleType or CandleType == 'Both')

    var ttBullishKicking = 'Kicking\nBullish reversal 53% of the time. The first day candlestick is a bearish marubozu candlestick with next to no upper or lower shadow and where the price opens at the day’s high and closes at the day’s low. The second day is a bullish marubozu pattern, with next to no upper or lower shadow and where the price opens at the day’s low and closes at the day’s high. Additionally, the second day gaps up extensively and opens above the opening price of the day before. This gap or window, as the Japanese call it, lies between day one and day two’s bullish candlesticks.'
    label.new(bar_index, patternLabelPosLow, text='K', style=label.style_label_up, color=label_color_bullish, textcolor=color.white, tooltip=ttBullishKicking)
C_KickingBearishNumberOfCandles = 2
C_MarubozuBullishShadowPercent = 5.0
C_MarubozuBearishKicking = C_LongBody and C_UpShadow <= C_MarubozuBullishShadowPercent / 100 * C_Body and C_DnShadow <= C_MarubozuBullishShadowPercent / 100 * C_Body
C_MarubozuWhiteBearish = C_MarubozuBearishKicking and C_WhiteBody
C_MarubozuBlackBearishKicking = C_MarubozuBearishKicking and C_BlackBody
C_KickingBearish = C_MarubozuWhiteBearish[1] and C_MarubozuBlackBearishKicking and low[1] > high
alertcondition(C_KickingBearish, title='Kicking – Bearish', message='New Kicking – Bearish pattern detected')
if C_KickingBearish and KickingInput and ('Bearish' == CandleType or CandleType == 'Both')

    var ttBearishKicking = 'Kicking\nBearish reversal 54% of the time. A bearish kicking pattern will occur, subsequently signaling a reversal for a new downtrend. The first day candlestick is a bullish marubozu. The second day gaps down extensively and opens below the opening price of the day before. There is a gap between day one and two’s bearish candlesticks.'
    label.new(bar_index, patternLabelPosHigh, text='K', style=label.style_label_down, color=label_color_bearish, textcolor=color.white, tooltip=ttBearishKicking)
    var ttAllCandlestickPatterns = 'All Candlestick Patterns\n'
    label.new(bar_index, patternLabelPosLow, text='Collection', style=label.style_label_up, color=label_color_neutral, textcolor=color.white, tooltip=ttAllCandlestickPatterns)
